name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - blazor-wasm-aot
          - blazor-wasm-aot2
          - blazor-wasm
          - functions-dotnet6-inproc
          - functions-dotnet6-isolated
          - functions-dotnetcore3.1-inproc
          - functions-node12
          - functions-python3.8
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.script }}
        continue-on-error: true
        run: |
          chmod +x *
          docker run --rm -v $(pwd):/scripts mcr.microsoft.com/oryx/build:azfunc-jamstack-20220131.3 /scripts/${{ matrix.script }}.sh
